application: clothedstone
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: play.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest